@tool
@icon("res://addons/rpg_actor/assets/RpgActor.svg")
extends Node
## [RpgActor] is meant to wrap the [url=https://rpg.actor/dev-guide#atproto-api]rpg.actor API[/url].


## The [member RpgActor.base_api] is the base API for rpg.actor calls.
## [br][br]
## This value can be changed in Project Settings under Rpg Actor -> API.
var base_api: String:
	get: return ProjectSettings.get_setting("rpg_actor/api", "https://rpg.actor/api")

## This is an internal cache for all sprite [Image] buffers generated by [method RpgActor.get_sprite] to cut down on spamming API calls.
var _sprite_cache: Dictionary = {}


# Registry API


## If [param full] is true, this method returns the full cached actor data for all actors. Otherwise, it returns all indexed actor DIDd with collection metadata.
## [br][br]
## [code lang=text]GET /api/actors[/code]
## [br]
## [code lang=text]GET /api/actors/full[/code]
func get_actors(full: bool = false) -> Dictionary:
	var endpoint = "actors"
	if full:
		endpoint += "/full"
	return await XRPC._http_request("%s/%s" % [base_api, endpoint])


## This method searchs actors by handle or display name (min 2 chars, max 10 results).
## [br][br]
## [code lang=text]GET /api/search?q=...[/code]
func search_actors(query: String) -> Array:
	if query == null or query.is_empty():
		return []
	if query.length() < 2:
		push_error("Query must be atleast 2 characters in length!")
	return await XRPC._http_request("%s/%s%s" % [base_api, "search?q=", query])


## This method gets the registry summary metrics (actor count, system count, master authority count).
## [br][br]
## [code lang=text]GET /api/stats[/code]
func metrics() -> Dictionary:
	return await XRPC._http_request("%s/%s" % [base_api, "stats"])


## This method gets the service health, actor/master counts, and uptime.
## [br][br]
## [code lang=text]GET /api/health[/code]
func health() -> Dictionary:
	return await XRPC._http_request("%s/%s" % [base_api, "health"])


# Masters API


## This method gets the master validations for a specific [param player_did] (add &verify=true to check live).
## [br][br]
## [code lang=text]GET /api/masters?player=did:...[/code]
func get_masters_for_player(player_did: String) -> Dictionary:
	validate_did(player_did)
	return await XRPC._http_request("%s/%s%s" % [base_api, "masters?player=", player_did])


## This method gets all players validated by a specific master/GM.
## [br][br]
## [code lang=text]GET /api/masters/by-authority?authority=did:...[/code]
func get_masters_by_authority(authority_did: String) -> Dictionary:
	validate_did(authority_did)
	return await XRPC._http_request("%s/%s%s" % [base_api, "masters/by-authority?authority=", authority_did])


# Sprites and Media API


## This method gets the standard 144×192 PNG sprite sheet for any actor.
## [br][br]
## [color=gold]Warning[/color]: rpg.actor allows for custom sprites to be uploaded of any size. This may be incompatible or produce inaccurate spritesheets for larger or custom sprites.
## [br][br]
## [code lang=text]GET /api/sprite/normalized?did=...[/code]
func get_sprite(did: String) -> PackedByteArray:
	validate_did(did)
	var data = await XRPC._http_request("%s/%s%s" % [base_api, "sprite/normalized?did=", did])
	return _sprite_cache.get_or_add(did, data)


## This method gets the generated 1200×630 Open Graph card image (sprite + stats).
## [br][br]
## [code lang=text]GET /api/og/image?id=...[/code]
func get_open_graphic_card(did: String) -> PackedByteArray:
	validate_did(did)
	return await XRPC._http_request("%s/%s%s" % [base_api, "og/image?id=", did])


# Equipment API


## This method gets the equipment index summary — total gives, items, providers, and known provider list.
## [br][br]
## [code lang=text]GET /api/equipment[/code]
func get_equipment() -> Dictionary:
	return await XRPC._http_request("%s/%s" % [base_api, "equipment"])


## This method gets all items owned by a player and all gives addressed to them, across all providers.
## [br][br]
## [code lang=text]GET /api/equipment?player=did:...[/code]
func get_equipment_by_player(did: String) -> Dictionary:
	return await XRPC._http_request("%s/%s%s" % [base_api, "equipment?player=", did])


## This method gets all gives issued by a specific provider.
## [br][br]
## [code lang=text]GET /api/equipment?provider=did:...[/code]
func get_equipment_by_provider(did: String) -> Dictionary:
	return await XRPC._http_request("%s/%s%s" % [base_api, "equipment?provider=", did])


# Creator API


## This method gets the current pricing tiers, early bird availability, and PDS status.
## [br][br]
## [code lang=text]GET /api/creator/pricing[/code]
func get_creator_pricing() -> Dictionary:
	return await XRPC._http_request("%s/%s" % [base_api, "creator/pricing"])


## This method checks if a DID is a registered creator account.
## [br][br]
## [code lang=text]GET /api/creator/check?did=...[/code]
func check_creator(did: String) -> bool:
	validate_did(did)
	var data = await XRPC._http_request("%s/%s%s" % [base_api, "creator/check?did=", did])
	return data.get("isCreator", false)


# Account API


## This method provides a password login for rpg.actor native accounts.
## [br][br]
## [code lang=text]POST /api/pds-login[/code]
## @experimental
func pds_login(handle: String, password: String) -> Dictionary:
	validate_handle(handle)
	return await XRPC._http_request("%s/%s" % [base_api, "pds-login"], HTTPClient.METHOD_POST, [
		"Content-Type: application/json"
	], {
		"handle": handle,
		"password": password
	})


## This method updates the PDS account email (requires DID + current password).
## [br][br]
## [code lang=text]POST /api/account/update-email[/code]
## @experimental
func update_email(did: String, password: String, email: String) -> Dictionary:
	validate_did(did)
	return await XRPC._http_request("%s/%s" % [base_api, "account/update-email"], HTTPClient.METHOD_POST, [
		"Content-Type: application/json"
	], {
		"did": did,
		"password": password,
		"email": email
	})


## This method change the account password (requires DID + current + new password).
## [br][br]
## [code lang=text]POST /api/account/change-password[/code]
## @experimental
func change_password(did: String, current_password: String, new_password: String) -> Dictionary:
	validate_did(did)
	return await XRPC._http_request("%s/%s" % [base_api, "account/change-password"], HTTPClient.METHOD_POST, [
		"Content-Type: application/json"
	], {
		"did": did,
		"current_password": current_password,
		"new_password": new_password
	})


## This method triggers an immediate cache refresh. Should be called after a stat or sprite mutation.
## [br][br]
## [code lang=text]POST /api/refresh-actor[/code]
## @experimental
func refresh_actor(did: String) -> Variant:
	validate_did(did)
	var data = await XRPC._http_request("%s/%s" % [base_api, "refresh-actor"], HTTPClient.METHOD_POST, [
		"Content-Type: application/json"
	], {
		"did": did
	})
	if data is Dictionary and data.get("status") == "ok":
		_sprite_cache.erase(did)
	return data


## This method submits a [url=https://rpg.actor/contact]contact form[/url] like that on the site.
## [br][br]
## [code lang=text]POST /api/contact[/code]
## @experimental
func contact(email: String, subject: String, message: String, handle: String = "") -> Dictionary:
	var data = {
		"email": email,
		"subject": subject,
		"message": message
	}
	if !handle.is_empty():
		validate_handle(handle)
		data.set("handle", handle)
	return await XRPC._http_request("%s/%s" % [base_api, "contact"], HTTPClient.METHOD_POST, [
		"Content-Type: application/json"
	], data)


# Internal


## This method is used internally for a quick and dirty validation check for passed in AT Protocol [param handle]s.
func validate_handle(handle: String) -> void:
	if handle.split(".").size() != 3:
		push_error("Provided handle %s is not a valid AT protocol handle!" % [handle])


## This method is used internally for a quick and dirty validation check for passed in AT Protocol [param did]s.
func validate_did(did: String) -> void:
	var parts = did.split(":")
	if parts.size() != 3 or parts[0] != "did" or parts[1] != "plc":
		push_error("Provided DID %s is not a valid AT protocol DID string!" % [did])
